Repository sainirock61/practicals, pull requests merged in 2022-10, with the labels that each got.

#133 Update LENGTH.CPP
  LENGTH.CPP
Labels: enhancement, good first issue, hacktoberfest-accepted

#132 Update Compound Interest
  Compound Interest
Labels: good first issue, hacktoberfest-accepted

#130 intersection point of two linked
  intersection point of two LL
Labels: enhancement, hacktoberfest-accepted

#136 Create Rotate a Linked List
  Rotate a Linked List
Labels: enhancement, good first issue, hacktoberfest-accepted

#135 Reverse a Linked List in groups of given size
  linearsearch.cpp
Labels: help wanted, hacktoberfest-accepted

#134 Merge Sort for Doubly Linked List
  Program7.cpp
Labels: enhancement, help wanted, hacktoberfest-accepted

#139 Create Fitting Shelves Problem
  Fitting Shelves Problem
Labels: enhancement, good first issue, hacktoberfest-accepted

#138 Create Water Connection Problem
  Water Connection Problem
Labels: enhancement, hacktoberfest-accepted

#137 Create Playfair Cipher
  Playfair Cipher
Labels: enhancement, hacktoberfest-accepted

#141 Create set of points
  New Algos/set of points
Labels: enhancement, hacktoberfest-accepted

#143 Create Maximum Intersection
  New Algos/Maximum Intersection
Labels: enhancement, hacktoberfest-accepted

#142 Create Klee’s Algorithm
  New Algos/Klee’s Algorithm
Labels: enhancement, hacktoberfest-accepted

#145 Update binarysearch.cpp
  binarysearch.cpp
Labels: help wanted, hacktoberfest-accepted

#146 Update swaping_using_pointers.cpp
  swaping_using_pointers.cpp
Labels: enhancement, help wanted, hacktoberfest-accepted

#147 Update Roots of Quadratic Equation
  Roots of Quadratic Equation
Labels: enhancement, help wanted, hacktoberfest-accepted

#148 Update Program8.cpp
  Program8.cpp
Labels: enhancement, help wanted, hacktoberfest-accepted

#149 Create K Centers Problem
  New Algos/K Centers Problem
Labels: help wanted, hacktoberfest-accepted

#150 Create Contiguous Subarray.cpp
  New Algos/Contiguous Subarray.cpp
Labels: help wanted, hacktoberfest-accepted

#151 Create Binary Insertion Sort
  New Algos/Binary Insertion Sort
Labels: enhancement, good first issue, hacktoberfest-accepted

#152 Create K-ary Heap
  New Algos/K-ary Heap
Labels: enhancement, good first issue, hacktoberfest-accepted

#153 Create Binomial Heap
  New Algos/Binomial Heap
Labels: enhancement, good first issue, hacktoberfest-accepted

#157 Create AKS Primality Test.cpp
  New Algos/AKS Primality Test.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#155 Create N-bonacci Numbers.cpp
  New Algos/N-bonacci Numbers.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#154 Create Little and Big Endian Mystery
  New Algos/Little and Big Endian Mystery
Labels: enhancement, good first issue, hacktoberfest-accepted

#159 Added a C++ Program for Circular Linked List
  circularlinkedlist.cpp
Labels: enhancement, hacktoberfest-accepted

#160 Create transpose-graph.cpp
  New Algos/transpose-graph.cpp
Labels: enhancement, hacktoberfest-accepted

#167 Create Pollard’s-Rho.cpp
  New Algos/Pollard’s-Rho.cpp
Labels: enhancement, hacktoberfest-accepted

#163 Create Topological-Sorting.cpp
  New Algos/Topological-Sorting.cpp
Labels: enhancement, hacktoberfest-accepted

#173 Create Modular multiplicative inverse.cpp
  top-10/Modular multiplicative inverse.cpp
Labels: enhancement, hacktoberfest-accepted

#161 Create Bidirectional Search.cpp
  New Algos/Bidirectional Search.cpp
Labels: enhancement, hacktoberfest-accepted

#162 Create stepping-numbers.cpp
  New Algos/stepping-numbers.cpp
Labels: enhancement, hacktoberfest-accepted

#175 Create Euler’s Totient Function.cpp
  Euler’s Totient Function.cpp
Labels: enhancement, hacktoberfest-accepted

#174 Create Compute nCr % p.cpp
  Compute nCr % p.cpp
Labels: enhancement, hacktoberfest-accepted

#172 Create Chinese Remainder Theorem.cpp
  top-10/Chinese Remainder Theorem.cpp
Labels: enhancement, hacktoberfest-accepted

#171 Create Floyd Warshall.cpp
  top-10/Floyd Warshall.cpp
Labels: enhancement, hacktoberfest-accepted

#169 Create Depth First Search.cpp
  top-10/Depth First Search.cpp
Labels: enhancement, hacktoberfest-accepted

#168 Create Breadth First Search.cpp
  top-10/Breadth First Search.cpp
Labels: enhancement, hacktoberfest-accepted

#166 Create Modular-multiplicative-inverse.cpp
  New Algos/Modular-multiplicative-inverse.cpp
Labels: enhancement, hacktoberfest-accepted

#165 Create Floyd Warshall Algorithm.cpp
  New Algos/Floyd Warshall Algorithm.cpp
Labels: enhancement, hacktoberfest-accepted
